### PR TITLE
defconfig  for BeagleV

### PR DESCRIPTION
**Pull request by tekkamanninja**
Fix starfive vin driver bug(remove MODULE_SUPPORTED_DEVICE(revoked))(merged)
**Add a defconfig for Fedora kernel(preparing for RPM)**
Add Drew's gpio-starfive-jh710: fix "registered 0 GPIOs" message (merged )

### CODE REVIEW

**Comment by esmil** [comment]
@tekkamanninja Hmm.. this `starfive_jh7100_starlight_fedora_defconfig` does not seem to be a defconfig a full .config file.
The difference is that a .config file contains all the Kconfig options written out, but a defconfig only contains the difference from the Kconfig defaults.

You can get a defconfig from .config by doing
```
make oldconfig
make savedefconfig
mv defconfig arch/riscv/configs/starfive_jh7100_starlight_fedora_defconfig
```

**Comment by esmil** [comment]
I've pushed the two other commits now, thanks.

**Comment by tekkamanninja** [comment]
> @tekkamanninja Hmm.. this `starfive_jh7100_starlight_fedora_defconfig` does not seem to be a defconfig, but a full .config file.
> The difference is that a .config file contains all the Kconfig options written out, but a defconfig only contains the difference from the Kconfig defaults.
> 
> You can get a defconfig from .config by doing
> 
> ```
> make oldconfig
> make savedefconfig
> mv defconfig arch/riscv/configs/starfive_jh7100_starlight_fedora_defconfig
> ```

Great thanks , will do :-)

**Comment by tekkamanninja** [comment]
@esmil  Hi, I have updated to 5.14-rc1 , and have tried it on BeagleV, work well. 

> @tekkamanninja Hmm.. this `starfive_jh7100_starlight_fedora_defconfig` does not seem to be a defconfig, but a full .config file.
> The difference is that a .config file contains all the Kconfig options written out, but a defconfig only contains the difference from the Kconfig defaults.
> 
> You can get a defconfig from .config by doing
> 
> ```
> make oldconfig

why do we need this "oldconfig" ? 
I think savedefconfig should just work.

> make savedefconfig
> mv defconfig arch/riscv/configs/starfive_jh7100_starlight_fedora_defconfig
> ```

**Comment by esmil** [comment]
> @esmil Hi, I have updated to 5.14-rc1 , and have tried it on BeagleV, work well.
> 
> > @tekkamanninja Hmm.. this `starfive_jh7100_starlight_fedora_defconfig` does not seem to be a defconfig, but a full .config file.
> > The difference is that a .config file contains all the Kconfig options written out, but a defconfig only contains the difference from the Kconfig defaults.
> > You can get a defconfig from .config by doing
> > ```
> > make oldconfig
> > ```
> 
> why do we need this "oldconfig" ?
> I think savedefconfig should just work.

That's just to make sure your .config file is up to date with the kernel tree you've checked out.

**Comment by esmil** [comment]
Thanks. Rewrote the commit message a bit.

**Comment by tekkamanninja** [comment]
> > @esmil Hi, I have updated to 5.14-rc1 , and have tried it on BeagleV, work well.
> > > @tekkamanninja Hmm.. this `starfive_jh7100_starlight_fedora_defconfig` does not seem to be a defconfig, but a full .config file.
> > > The difference is that a .config file contains all the Kconfig options written out, but a defconfig only contains the difference from the Kconfig defaults.
> > > You can get a defconfig from .config by doing
> > > ```
> > > make oldconfig
> > > ```
> > 
> > 
> > why do we need this "oldconfig" ?
> > I think savedefconfig should just work.
> 
> That's just to make sure your .config file is up to date with the kernel tree you've checked out.

Ah,  yes, thanks!  We always used menuconfig to update it and check manually  :-)

**Pull request closed without merging**
