### PR TITLE
Module fix for starfive_fb

### PR DESCRIPTION
**Pull request by sarnold**

### CODE REVIEW

**Comment by sarnold** [comment]
Lemme fix this (actually I didn't want that first commit on this branch).

**Comment by esmil** [comment]
Hi Steve. Thanks for the fix. Yeah, I was going to ask if you'd tried the starlight_defconfig I added here. I can just cherry-pick the module fix if that's easier.

**Comment by sarnold** [comment]
Already done ;)

**Comment by esmil** [comment]
Great thanks! I ended up reordering the commits anyway. Hope you don't mind.

**Pull request closed without merging**
