### PR TITLE
config: first attempt to enable jh7100

### PR DESCRIPTION
**Pull request by mcd500**
Signed-off-by: Akira Tsukamoto <akira.tsukamoto@gmail.com>

### CODE REVIEW

**Comment by esmil** [comment]
@mcd500 Hi Akira. Thank you for your pull request. I was actually working on making it easier to use this branch already. Do you mind trying the [defconfig][] branch to see if that works for you? It also includes build instructions in the [README].

[defconfig]: https://github.com/esmil/linux/tree/defconfig
[README]: https://github.com/esmil/linux/tree/defconfig#readme

**Comment by mcd500** [comment]
@esmil booting successfully after replacing the kernel in fedora rootfs and the eth0 is working fine without link down.
Thank you for porting on 5.12.
```
Build date: Mon Apr 19 05:47:05 UTC 2021

Kernel 5.12.0-291806-g79e951c6e762-dirty on an riscv64 (ttyS0)

The root password is 'starfive'.
root password logins are disabled in SSH starting Fedora 31.
User 'riscv' with password 'starfive' in 'wheel' group is provided.

To install new packages use 'dnf install ...'

To upgrade disk image use 'dnf upgrade --best'

If DNS isn��’t working, try editing ��‘/etc/yum.repos.d/fedora-riscv.repo��’.

For updates and latest information read:
https://fedoraproject.org/wiki/Architectures/RISC-V

Fedora/RISC-V
-------------
Koji:               http://fedora.riscv.rocks/koji/
SCM:                http://fedora.riscv.rocks:3000/
Distribution rep.:  http://fedora.riscv.rocks/repos-dist/
Koji internal rep.: http://fedora.riscv.rocks/repos/
fedora-starfive login: root
Password: 
[  153.359895] systemd-xdg-autostart-generator[460]: Not generating service for XDG autos.
[  153.375984] systemd-xdg-autostart-generator[460]: Not generating service for XDG autos.
[  153.392074] systemd-xdg-autostart-generator[460]: Not generating service for XDG autos.
Last login: Tue May 11 17:16:54 on ttyS0
[root@fedora-starfive ~]# ifconfig 
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.112  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::7d92:7fe8:3d9e:a387  prefixlen 64  scopeid 0x20<link>
        ether 2c:f7:f1:1b:e4:44  txqueuelen 1000  (Ethernet)
        RX packets 34  bytes 4688 (4.5 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 40  bytes 4022 (3.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 20 
```

**Comment by mcd500** [comment]
@esmil The reboot is also working just updating with the built kernel and dtb.
```
[  172.914659] systemd-shutdown[1]: Detaching DM devices.
[  172.920474] systemd-shutdown[1]: All DM devices detached.
[  172.925998] systemd-shutdown[1]: All filesystems, swaps, loop devices and DM devices d.
[  173.284044] systemd-shutdown[1]: Syncing filesystems and block devices.
[  173.291311] systemd-shutdown[1]: Rebooting.
[  173.306069] reboot: Restarting system
[ bootloader version:210209-4547a8d
                                   ddr 0x00000000, 1M test
ddr 0x00100000, 2M test
DDR clk 2133M,Version: 210302-5aea32f
0 crc flash: 9a132612, crc ddr: 9a132612
                                        crc check PASSED

                                                        bootloader.

OpenSBI v0.9
   ____                    _____ ____ _____
  / __ \                  / ____|  _ \_   _|
 | |  | |_ __   ___ _ __ | (___ | |_) || |
 | |  | | '_ \ / _ \ '_ \ \___ \|  _ < | |
 | |__| | |_) |  __/ | | |____) | |_) || |_
  \____/| .__/ \___|_| |_|_____/|____/_____|
        | |
        |_|

```

**Comment by esmil** [comment]
Wow, github is drunk. Akira told me the starlight_defconfig works fine, so let's just close this.

**Pull request closed without merging**
