### PR TITLE
rename defconfig for beaglev starlight

### PR DESCRIPTION
**Pull request by pdp7**
The name of the board is [BeagleV Starlight](https://github.com/beagleboard/beaglev-starlight) so rename the defconfig to represent that.

NOTE: I also changed the LOCALVERSION in the defconfig but that made me wonder, should we even be setting LOCALVERSION in the defconfig?

### CODE REVIEW

**Comment by geertu** [comment]
> The name of the board is [BeagleV Starlight](https://github.com/beagleboard/beaglev-starlight) so rename the defconfig to represent that.
> 
> NOTE: I also changed the LOCALVERSION in the defconfig but that made me wonder, should we even be setting LOCALVERSION in the defconfig?

I like to see easily from which config a board was booted, especially if there are board-specific configs and configs for all or a group of boards.  It may give a clue when there is a problem.

Yeah, I know some people don't like doing that...

**Comment by esmil** [comment]
@geertu Would CONFIG_LOCALVERSION="-beaglev-starlight" be a reasonable compromise?

@pdp7 How about changing the name to just `beaglev_defconfig` ?

**Comment by pdp7** [comment]
> @geertu Would CONFIG_LOCALVERSION="-beaglev-starlight" be a reasonable compromise?
> 
> @pdp7 How about changing the name to just `beaglev_defconfig` ?

Yes,  `beaglev_defconfig`  be good.

At first, I was thinking maybe ` beaglev_jh7100_defconfig` would be better but then I realized that we should be able to support both jh7100 and the jh7110 with one defconfig.  The device tree is really where the differentiation will occur.

**Comment by mcd500** [comment]
@esmil This is off the topic, but after the latest rebase, the reboot is not working.
```
systemd-shutdown[1]: All DM devices detached.
systemd-shutdown[1]: All filesystems, swaps, loop devices and DM devices detached.
systemd-shutdown[1]: Syncing filesystems and block devices.
systemd-shutdown[1]: Rebooting.
reboot: Restarting system
mmc0: card 1234 removed
```
Which used to reboot right after the above message.

**Comment by mcd500** [comment]
@esmil Please ignore my previous comment, I found that I had a typo when copying dtb after the recent name change,,, my bad.

**Comment by mcd500** [comment]
@pdp7 @esmil Should be good to unify the name of both from the `starlight_defconfig` to `beaglev_defconfig` and from the `jh7100-beaglev-starlight.dts` to `jh7100-beaglev.dts`?

**Comment by esmil** [comment]
No, the device tree should still be `jh7100-beaglev-starlight` since that's the name of this board. The bborg foundation may make more BeagleV branded boards.

**Comment by esmil** [comment]
The defconfig is now `beaglev_defconfig` and it has `CONFIG_LOCALVERSION="-beaglev"`.

**Pull request closed without merging**
