### PR TITLE
Beaglev misc fixes

### PR DESCRIPTION
**Pull request by geertu**
To be squashed into the original commits that introduced the issues.
Thanks!

### CODE REVIEW

**Comment by esmil** [comment]
Thanks! I totally forgot about `squash!` and similar prefixes. That's super neat that it works over pull requests too :)

**Comment by geertu** [comment]
> Thanks! I totally forgot about `squash!` and similar prefixes. That's super neat that it works over pull requests too :)

And you don't have to write them yourself! Just use "git commit --squash <sha1>" or "... --fixes <sha1>".
To squash with the latest commit touching a particular file, I have created a git alias:
```
$ git help squash-latest
'squash-latest' is aliased to '!bash -c "git commit -p --squash $(git log -1 --format=%h $1) -- $1" #'
```

**Comment by esmil** [comment]
That's genius. I can't believe I didn't think of that :+1:

**Review by pdp7 — COMMENTED** [review]
@geertu I'll change [my gpio patch series](https://lore.kernel.org/linux-gpio/20210701002037.912625-1-drew@beagleboard.org/#t) when I send v2 to have:
```
        clocks = <&clkgen JH7100_CLK_GPIO_APB>;
```
Should I add your SOB?

**Comment by geertu** [comment]
On Thu, Jul 8, 2021 at 8:56 PM Drew Fustini ***@***.***> wrote:
> @geertu I'll change my gpio patch series when I send v2 to have:
>
>         clocks = <&clkgen JH7100_CLK_GPIO_APB>;
>
> Should I add your SOB?

No, that's not needed for such a minor fix.

Gr{oetje,eeting}s,

                        Geert

-- 
Geert Uytterhoeven -- There's lots of Linux beyond ia32 -- ***@***.***

In personal conversations with technical people, I call myself a hacker. But
when I'm talking to journalists I just say "programmer" or something like that.
                                -- Linus Torvalds

**Pull request closed without merging**
