### PR TITLE
remove unused header gpio-starfive-vic.h

### PR DESCRIPTION
**Pull request by pdp7**
The commit that adds the starfive-jh7100 gpio driver:

ad78ee06db98750082ab52e23e4608a3787a3db4

still has the header file from the old VIC version before my cleanup and
renaming.  No header file is needed anymore so let's get rid of it.

Emil: please fixup the this commit so we jush have a single GPIO driver
commit.

Signed-off-by: Drew Fustini <drew@beagleboard.org>

### CODE REVIEW

**Comment by esmil** [comment]
@pdp7 I'll gladly fix up the gpio commit next time I rebase, but this certainly header isn't unused:
```
esmil@stitch~/linux$ git grep gpio-starfive-vic.h
drivers/i2c/busses/i2c-designware-master.c:#include <linux/gpio-starfive-vic.h>
drivers/i2c/busses/i2c-designware-platdrv.c:#include <linux/gpio-starfive-vic.h>
drivers/media/platform/starfive/imx219_mipi.c:#include <linux/gpio-starfive-vic.h>
drivers/media/platform/starfive/ov5640_dvp.c:#include <linux/gpio-starfive-vic.h>
drivers/media/platform/starfive/sc2235.c:#include <linux/gpio-starfive-vic.h>
drivers/video/fbdev/starfive/adv7513.c:#include <linux/gpio-starfive-vic.h>
drivers/video/fbdev/starfive/seeed5inch.c:#include <linux/gpio-starfive-vic.h>
```
I guess I'll just make it a separate commit.

**Comment by pdp7** [comment]
@esmil yes, I just noticed that to after running a full build.

It turns out the header is not actually used in the code for:
```
drivers/i2c/busses/i2c-designware-platdrv.c
drivers/media/platform/starfive/imx219_mipi.c
drivers/media/platform/starfive/sc2235.c
drivers/video/fbdev/starfive/adv7513.c
```

It is used in `drivers/i2c/busses/i2c-designware-master.c` code:
```

        if((dev->scl_gpio > 0) && (dev->sda_gpio > 0)) {
                SET_GPIO_dout_LOW(dev->scl_gpio);
                SET_GPIO_dout_LOW(dev->sda_gpio);
                SET_GPIO_doen_reverse_(dev->scl_gpio,1);
                SET_GPIO_doen_reverse_(dev->sda_gpio,1);             
                switch(dev->adapter.nr) {
                case 0:
                        SET_GPIO_doen_i2c0_pad_sck_oe(dev->scl_gpio);
                        SET_GPIO_doen_i2c0_pad_sda_oe(dev->sda_gpio);
                        SET_GPIO_i2c0_pad_sck_in(dev->scl_gpio);
                        SET_GPIO_i2c0_pad_sda_in(dev->sda_gpio);
                        break;
                case 1:
                        SET_GPIO_doen_i2c1_pad_sck_oe(dev->scl_gpio);
                        SET_GPIO_doen_i2c1_pad_sda_oe(dev->sda_gpio);
                        SET_GPIO_i2c1_pad_sck_in(dev->scl_gpio);
                        SET_GPIO_i2c1_pad_sda_in(dev->sda_gpio);
                        break;                                         
                case 2:
                        SET_GPIO_doen_i2c2_pad_sck_oe(dev->scl_gpio);  
                        SET_GPIO_doen_i2c2_pad_sda_oe(dev->sda_gpio);
                        SET_GPIO_i2c2_pad_sck_in(dev->scl_gpio);
                        SET_GPIO_i2c2_pad_sda_in(dev->sda_gpio);
                        break;
                case 3:
                        SET_GPIO_doen_i2c3_pad_sck_oe(dev->scl_gpio);
                        SET_GPIO_doen_i2c3_pad_sda_oe(dev->sda_gpio);
                        SET_GPIO_i2c3_pad_sck_in(dev->scl_gpio);
                        SET_GPIO_i2c3_pad_sda_in(dev->sda_gpio);
                        break;
                default:
```
this looks to me like it is just code copied from bootloader.  I think it is should be possible to convert it to correct Linux code but for now, yes, let's just have the header file in a separate commit.

**Comment by esmil** [comment]
Yeah, I think the proper solution is to not even have this code in the driver, but have a proper pinctrl driver and specify these settings in the device tree.

**Comment by pdp7** [comment]
@esmil yes, I going to work on the pinctrl driver after getting initial feedback on the gpio driver.  I want to discuss the FMUX with Linus W. to get his thoughts on best way to implement pinctrl.

I think we can just carry `gpio-starfive-vic.h` header and hack in `drivers/i2c/busses/i2c-designware-master.c` as downstream patches until I can get pinctrl to the point where it can replace that hacky code in `i2c-designware-master.c` with the correct pinctrl and gpio function calls.

**Comment by pdp7** [comment]
I am restructuring this into a gpio cleanup branch that I will push as a new PR so I am closing this one.

**Pull request closed without merging**
