### PR TITLE
StarFive JH7100 Clock Generator Driver

### PR DESCRIPTION
**Pull request by geertu**
This is a preliminary driver (incl. DT bindings) for the StarFive JH7100 Clock Generator, which is part of the PCR (Power/Clock/Reset) Management Unit.

For now, all clocks are implemented as fixed-factor clocks relative to osc0, based on the list of fixed-frequency clocks defined in jh7100.dtsi.  To be updated with the real clock topology and with actual clock register accesses when the documentation becomes available.

### CODE REVIEW

**Comment by pdp7** [comment]
Thanks, this boots successfully on my board

**Comment by pdp7** [comment]
@geertu do you think it makes sense for me to add clocks to the gpio yaml?
```diff
diff --git a/Documentation/devicetree/bindings/gpio/starfive,jh7100-gpio.yaml b/Documentation/devicetree/bindings/gpio/starfive,jh7100-gpio.yaml
index 8c9d14d9ac3b..f623d8b1fbf0 100644
--- a/Documentation/devicetree/bindings/gpio/starfive,jh7100-gpio.yaml
+++ b/Documentation/devicetree/bindings/gpio/starfive,jh7100-gpio.yaml
@@ -34,6 +34,9 @@ properties:
   "#interrupt-cells":
     const: 2
 
+  clocks:
+    maxItems: 1
+
 required:
   - compatible
   - reg
@@ -42,6 +45,7 @@ required:
   - "#interrupt-cells"
   - "#gpio-cells"
   - gpio-controller
+  - clocks
 
 additionalProperties: false
 
@@ -55,6 +59,7 @@ examples:
         interrupt-controller;
         #interrupt-cells = <2>;
         interrupts = <32>;
+        clocks = < NOT SURE WHAT TO PUT HERE >;
       };
```

**Comment by pdp7** [comment]
I am thinking  GPIO is using  clk_apb1_bus:
Screenshot from 2021-06-02 14-50-24
Screenshot from 2021-06-02 14-47-57
so it looks like it would be:
```
#define JH7100_CLK_APB1		<br class="Apple-interchange-newline">
```
and thus:
```diff
diff --git a/Documentation/devicetree/bindings/gpio/starfive,jh7100-gpio.yaml b/Documentation/devicetree/bindings/gpio/starfive,jh7100-gpio.yaml
index 8c9d14d9ac3b..f623d8b1fbf0 100644
--- a/Documentation/devicetree/bindings/gpio/starfive,jh7100-gpio.yaml
+++ b/Documentation/devicetree/bindings/gpio/starfive,jh7100-gpio.yaml
@@ -34,6 +34,9 @@ properties:
   "#interrupt-cells":
     const: 2
 
+  clocks:
+    maxItems: 1
+
 required:
   - compatible
   - reg
@@ -42,6 +45,7 @@ required:
   - "#interrupt-cells"
   - "#gpio-cells"
   - gpio-controller
+  - clocks
 
 additionalProperties: false
 
@@ -55,6 +59,7 @@ examples:
         interrupt-controller;
         #interrupt-cells = <2>;
         interrupts = <32>;
+        clocks = <&clkgen JH7100_CLK_APB1>;
       };
```

**Comment by geertu** [comment]
@pdp7
> so it looks like it would be:
> 
> ```
> #define JH7100_CLK_APB1		<br class="Apple-interchange-newline">
> ```
> 
> and thus:
> 
> ```diff
> diff --git a/Documentation/devicetree/bindings/gpio/starfive,jh7100-gpio.yaml b/Documentation/devicetree/bindings/gpio/starfive,jh7100-gpio.yaml
> index 8c9d14d9ac3b..f623d8b1fbf0 100644
> --- a/Documentation/devicetree/bindings/gpio/starfive,jh7100-gpio.yaml
> +++ b/Documentation/devicetree/bindings/gpio/starfive,jh7100-gpio.yaml
> @@ -34,6 +34,9 @@ properties:
>    "#interrupt-cells":
>      const: 2
>  
> +  clocks:
> +    maxItems: 1
> +
>  required:
>    - compatible
>    - reg
> @@ -42,6 +45,7 @@ required:
>    - "#interrupt-cells"
>    - "#gpio-cells"
>    - gpio-controller
> +  - clocks
>  
>  additionalProperties: false
>  
> @@ -55,6 +59,7 @@ examples:
>          interrupt-controller;
>          #interrupt-cells = <2>;
>          interrupts = <32>;
> +        clocks = <&clkgen JH7100_CLK_APB1>;
>        };
> ```

Yes, you could do that.  But currently the GPIO driver doesn't use this clock.  The only use I can see is for power management.
While we do know GPIO is clocked by APB1, we do not know yet whether it is clocked directly (always-on), or if the clock supply can be gated, through a (to be implemented) gateable child clock of APB1.
I wouldn't be surprised if the "PCR (Power/Clock/Reset) Management Unit" would provide invididual gateable clocks for each module, which would bring us to power-domains and Runtime PM.  Probably the PMR provides individual resets for each module, too.

Any chance we can get full documentation for the PMR block? Thanks!

**Comment by pdp7** [comment]
@geertu sorry for the delay, I have created 
https://github.com/starfive-tech/beaglev_doc/issues/15

I will use that to followup with starfive

**Comment by pdp7** [comment]
@geertu this now temporary documentation for clock and reset: https://forum.beagleboard.org/t/documentation-clock-tree-reset-tree-and-interrupt-list/30072?u=drewfustini  I will still followup about power domains

**Pull request merged**
